name: Makefile CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: python:3.11

    steps:
    - uses: actions/checkout@v3
    
    - name: Install
      run: make develop

    - name: Check
      run: make check
